"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def is_even(number):
    return True if number % 2 == 0 else False


def fibonacci_even(max_value):
    first = 1
    second = 2
    summ = 0

    while second <= max_value:

        if is_even(second):
            summ += second

        first, second = second, first + second
    return summ


if __name__ == "__main__":
    print(fibonacci_even(4000000))
